#!/bin/bash
#
# Generates a report on the number of concurrent sessions during each second.
# It reads an interval report with the following format.
#
# START_TIME STOP_TIME ...
#
# START_TIME is the time when a session started in seconds since the POSIX
# epoch. STOP_TIME is the time when the same session ended in seconds since the
# POSIX epoch.  The rest if the line is ignored.


main()
{
  local intervalsFile="$1"

  local lb
  lb=$(cut --delimiter ' ' --fields 1 "$intervalsFile" | sort --numeric-sort | head --lines 1)

  local max=0

  local counts
  
  local words
  while read -r -a words
  do
    local start=$((words[0] - lb))
    local stop=$((words[1] - lb))

    for t in $(seq "$start" "$stop")
    do
      counts["$t"]=$((counts[t] + 1))
    done

    if [ "$stop" -gt "$max" ]
    then
      max="$stop"
    fi
  done < "$intervalsFile"

  for t in $(seq 0 "$max")
  do
    printf '%d %d\n' $((lb + t)) $((counts[t] + 0))
  done
}


set -e
main "$@"
