#!/usr/bin/awk -f
#
# This script filters a stream of iRODS sessions for those generated by a given client.
#
# PARAMETERS:
#  user: The iRODS username to filter on


BEGIN {
  RS = "§";
  FS = "•";
}


$2 ~ "cuser=" user {
  printf "%s%s", RS, $0;
}
