#!/bin/bash

readonly ExecName=$(basename "$0")
readonly Version=1


show_help()
{
  cat <<EOF

$ExecName version $Version

Usage:
 $ExecName [options]

Updates the ICAT size information for the replicas of a set of data objects

Options:
 -j, --jobs  the number of fixes to perform simultaneously

 -h, --help     show help and exit
 -v, --version  show version and exit

Summary:
It reads a list of data object paths, one per line, from standard in. For each
replica, it updates the ICAT size information based on the size of the
corresponding file in storage.  No object name may have a carriage return in its
path. The user must be initialized with iRODS as an admin user. Finally, the
user must have passwordless access to the root account on the relevant storage
resources.
EOF
}


show_version()
{
  printf '%s\n' "$Version"
}


set -e

if ! opts=$(getopt --name "$ExecName" --options hj:v --longoptions help,jobs:,version -- "$@")
then
  printf '\n' >&2
  show_help >&2
  exit 1
fi

eval set -- "$opts"

while true
do
  case "$1" in
    -h|--help)
      show_help
      exit 0
      ;;
    -j|--jobs)
      readonly Jobs="$2"
      shift 2
      ;;
    -v|--version)
      show_version
      exit 0
      ;;
    --)
      shift
      break
      ;;
    *)
      show_help >&2
      exit 1
      ;;
  esac
done

readonly ExecPath=$(readlink --canonicalize "$0")
export EXEC_DIR
EXEC_DIR=$(dirname "$ExecPath")


exec_on_rs()
{
  local rs="$1"
  local cmd="$2"

  #shellcheck disable=SC2087
  ssh -q -t "$rs" <<EOSSH
if [[ "\$USER" = irods ]]
then
  $cmd
else
  sudo -i -u irods <<'EOSUDO'
$cmd
EOSUDO
fi
EOSSH
}


fix_cmd()
{
  local obj="$1"
  local resc="$2"
  local file="$3"

  cat <<EOCMD
readonly TmpFile='$file'.tmp

mv --no-clobber '$file' "\$TmpFile" && \\
  touch '$file' && \\
  (irsync -K -s -v -R '$resc' "\$TmpFile" i:'$obj'; mv "\$TmpFile" '$file')
EOCMD
}


FIX()
{
  local objPath="$1"

  printf '%s\n' "$objPath"

  while read -r rescHier storeHost filePath
  do
    local coordResc="${rescHier%%;*}"

    local fixCmd
    fixCmd=$(fix_cmd "$objPath" "$coordResc" "$filePath")

    exec_on_rs "$storeHost" "$fixCmd"
  done < <(cd "$EXEC_DIR" && ./get-replicas "$objPath")
}
export -f FIX


if [ -n "$Jobs" ]
then
  readonly JobsOpt="-j$Jobs"
else
  readonly JobsOpt=
fi

parallel --eta --no-notice --delimiter '\n' --max-args 1 "$JobsOpt" FIX > /dev/null
