#!/bin/bash

readonly ExecAbsPath=$(readlink --canonicalize "$0")
readonly ExecDir=$(dirname "$ExecAbsPath")

readonly LogDir=/var/lib/irods/iRODS/server/log
readonly LogBase=rodsLog

main()
{

  local host="$1"
  local logExtPat="$2"

  local password
  if [ "$#" -ge 3 ]
  then
    password="$3"
  fi

  local log
  for log in $(list_logs "$host" "$password" "$LogBase"."$logExtPat")
  do
    local logName
    logName=$(basename "$log")

    rcat_log "$host" "$password" "$log" \
      | "$ExecDir"/format-log-entries --assign YEAR="${logName:8:4}"

    printf 'gather_logs:  finished processing %s\n' "$logName" >&2
  done
}


list_logs()
{
  local host="$1"
  local password="$2"
  local logNamePat="$3"

  ssh -q -t "$host" <<EOF 2> /dev/null
printf '%s\n' "$password" | sudo -S find "$LogDir" -maxdepth 1 -name "$logNamePat" -type f | sort
EOF
}


rcat_log()
{
  local host="$1"
  local password="$2"
  local log="$3"

  ssh -q -t "$host" <<EOF 2> /dev/null
printf '%s\n' "$password" | sudo -S cat "$log"
EOF
}


main "$@"
