#!/usr/bin/env bash
#
# This program lists all of the replicas that are stale and were last modified
# before a certain day. It writes the list to stdout.
#
# Usage:
#  get-stale-replicas [CUTOFF-DATE]
#
# Parameters:
#  CUTOFF-DATE  only replicas modified prior to this date will be listed. The
#               default is no cutoff date
#
# Output:
#  It outputs one replica record per line. A record has two space-separated
#  columns. The first column is the resource hierarchy storing the replica, and
#  the second is the path to the corresponding data object.
#
# © 2026, The Arizona Board of Regents on behalf of The University of Arizona.
# For license information, see https://cyverse.org/license.

set -o errexit -o nounset -o pipefail

readonly DEFAULT_CUTOFF_DATE=tomorrow
readonly MAX_STALE_SLICE=1000

EXEC_DIR="$(dirname "$(realpath --canonicalize-existing "$0")")"
readonly EXEC_DIR

main() {
	local cutoffDate="$DEFAULT_CUTOFF_DATE"
	if (( $# >= 1 )); then
		cutoffDate="$1"
	fi

	local modTSCutoff
	modTSCutoff="$(date --date="$(date --iso-8601 --date="$cutoffDate")" +0%s)"

	local allStales
	readarray -t allStales < <(get_stales)

	if [[ -z "${allStales[*]-}" ]]; then
		return
	fi

	local oldStales
	readarray -t oldStales < <(filter_old_stales "$modTSCutoff" "${allStales[@]}")

	if [[ -z "${oldStales[*]-}" ]]; then
		return
	fi

	map_resources "${oldStales[@]}"
}

filter_old_stales() {
	local modCutoff="$1"; shift
	local allStales=( "$@" )

	local numStales=${#allStales[@]}
	printf '%s stale replicas\n' "$numStales" >&2

	local idx
	for (( idx=0; idx<numStales; idx+=MAX_STALE_SLICE )); do
		local slice=MAX_STALE_SLICE
		if (( numStales < idx + slice )); then
			slice=$(( numStales - idx ))
		fi

		printf 'processing %s - %s\n' $(( idx + 1 )) $(( idx + slice )) >&2
		get_fresh "$modCutoff" "$(fmt_query_list "${allStales[@]:$idx:$slice}")"
	done
}

get_fresh() {
	local modCutoff="$1"
	local idList="$2"

	"$EXEC_DIR"/quest %s <<EOF
select DATA_ID
where DATA_REPL_STATUS = '1' and DATA_MODIFY_TIME < '$modCutoff' and DATA_ID in ($idList)"
EOF
}

get_stales() {
	"$EXEC_DIR"/quest %s <<< "select DATA_ID where DATA_REPL_STATUS = '0'"
}

map_resources() {
	local oldStales=( "$@" )

	local numStales=${#oldStales[@]}
	printf '%s old stale replicas\n' "$numStales" >&2

	local idx
	for (( idx=0; idx < numStales; idx+=MAX_STALE_SLICE )); do
		local slice=MAX_STALE_SLICE
		if (( numStales < idx + slice )); then
			slice=$(( numStales - idx ))
		fi

		printf 'processing %s - %s\n' $(( idx + 1 )) $(( idx + slice )) >&2
		get_stale_resc_mapping "$(fmt_query_list "${oldStales[@]:$idx:$slice}")"
	done
}

get_stale_resc_mapping() {
	local idList="$1"

	"$EXEC_DIR"/quest '%s %s/%s' <<EOF
select DATA_RESC_HIER, COLL_NAME, DATA_NAME where DATA_REPL_STATUS = '0' and DATA_ID in ($idList)
EOF
}

fmt_query_list() {
	printf $'\'%s\'\n' "$@" | paste --serial --delimiter ,
}

main "$@"
