#!/usr/bin/env bash
#
# © 2026, The Arizona Board of Regents on behalf of The University of Arizona.
# For license information, see https://cyverse.org/license.

show_help() {
	cat <<EOF

$ExecName version $Version

Usage:
 $ExecName [options] <src_resc> <dest_resc>

Moves replicas from one storage resource to another. It will not move any
replica associated with a data object that has a replica on the destination
resource.

Parameters:
 <src_resc>   the name of the resource where replicas are moved from
 <dest_resc>  the name of the storage resource where replicas are moved to

Options:
 -c, --collection <collection>  only move replicas associated with data objects
                                in the collection <collection>
 -d, --dbms <host>              connect to the ICAT's DBMS on the host <host>
                                instead of the PostgreSQL default
 --dbms-port <port>             connect to the ICAT's DBMS listening on TCP port
                                <port> instead of the PostgreSQL default
 -m, --multiplier <multiplier>  a multiplier on the number of processes to run
                                at once
 -U, --user <user>              authorize the DBMS connection as user <user>
                                instead of the default

 -h, --help     show help and exit
 -v, --version  show version and exit
EOF
}

set -o errexit -o nounset -o pipefail

ExecName="$(basename "$0")"
readonly ExecName

export PGHOST PGPORT PGUSER

readonly DefaultMult=1
readonly Log=3          # Redirect stdout to FD 3 to use as a logging channel
readonly Version=1

declare ObjectList

main() {
	declare -A optMap=(
		[collection]=''
		[dest-resc]=''
		[help]=''
		[multiplier]="$DefaultMult"
		[src-resc]=''
		[version]='' )

	if ! resolve_opts optMap "$@"; then
		show_help >&2
		return 1
	fi

	if [[ -n "${optMap[help]}" ]]; then
		show_help
	elif [[ -n "${optMap[version]}" ]]; then
		printf '%s\n' "$Version"
	else
		move \
			"${optMap[collection]}" \
			"${optMap[src-resc]}" \
			"${optMap[dest-resc]}" \
			"${optMap[multiplier]}"
	fi
}



move() {
	local coll="$1"
	local srcResc="$2"
	local destResc="$3"
	local mult="$4"

	if [[ "$srcResc" == "$destResc" ]]; then
		printf 'The destination resource, %s, cannot be the same as the source resource, %s.\n' \
				"$destResc" "$srcResc" \
			>&2

		return 1
	fi

	if ! [[ "$mult" =~ ^[1-9][0-9]* ]]; then
		printf 'The -m option value must be a positive number. The given value was %s.\n' "$mult" >&2
		return 1
	fi

	if ! iadmin lz &> /dev/null; then
		printf "aren't authenticated as a rodsadmin user\n" >&2
		return 1
	fi

	if ! psql ICAT <<<'' &> /dev/null; then
		printf "aren't able to connect to the ICAT DB as the %s without a password\n" "$PGUSER" >&2
		return 1
	fi

	eval "exec $Log>&1"

	ObjectList="$(mktemp)"
	readonly ObjectList
	trap 'finish "$ObjectList"' EXIT

	local collCond
	if [[ -n "$coll" ]]; then
		collCond="c.coll_name = '$coll' OR c.coll_name LIKE '$coll/%'"
	else
		collCond=TRUE
	fi

	printf 'Checking to see if all data objects can be physically moved...\n' >&2

	local unmovableCount
	unmovableCount="$(count_unmovable "$collCond" "$srcResc" "$destResc")"

	if (( unmovableCount > 0 )); then
		cat <<EOF >&2
WARNING: NOT ALL DATA OBJECTS COULD BE MOVED BECAUSE REPLICAS ARE ALREADY ON THE
DESTINATION RESOURCE
EOF
	fi

	printf 'Retrieving data objects to physically move...\n' >&2

	psql --no-align --quiet --tuples-only --record-separator-zero --field-separator ' ' ICAT \
		> "$ObjectList" \
		<<EOSQL
BEGIN;

CREATE TEMPORARY TABLE src_data (id) AS
SELECT d.data_id
	FROM r_data_main AS d JOIN r_coll_main AS c ON c.coll_id = d.coll_id
	WHERE ($collCond) AND ($(mk_resc_restrict_cond resc_id "$srcResc"))
EXCEPT SELECT d.data_id
	FROM r_data_main AS d JOIN r_coll_main AS c ON c.coll_id = d.coll_id
	WHERE ($collCond) AND resc_id = (SELECT resc_id FROM r_resc_main WHERE resc_name = '$destResc');
CREATE INDEX src_data_idx ON src_data (id);

SELECT r.resc_name, d.data_size, c.coll_name || '/' || d.data_name
FROM r_resc_main AS r
	JOIN r_data_main AS d ON d.resc_id = r.resc_id
	JOIN r_coll_main AS c ON c.coll_id = d.coll_id
	JOIN src_data AS s ON s.id = d.data_id
WHERE ($collCond) AND ($(mk_resc_restrict_cond r.resc_id "$srcResc"));

ROLLBACK;
EOSQL

	local tot
	tot="$(count_list < "$ObjectList")"
	printf '%d data objects to physically move\n' "$tot" >&2

	local cnt=0

	local srcStoreRescs
	readarray -t srcStoreRescs <<< "$(list_src_resc < "$ObjectList")"

	local sr
	for sr in "${srcStoreRescs[@]}"; do
		local so
		so="$(mktemp)"
		sed --null-data --quiet 's/^'"$sr"' //p' < "$ObjectList" > "$so"

		local st
		st="$(count_list < "$so")"
		printf '\n%d data objects on %s to physically move\n' "$st" "$sr" >&2

		if (( st > 0 )); then
			local sc=0

			# 16 1-threaded
			sc="$(select_cohort "$destResc" "$sr" "$sc" "$st" "$mult" 16  0  1 < "$so")"

			# 8 2-threaded
			sc="$(select_cohort "$destResc" "$sr" "$sc" "$st" "$mult"  8  1  2 < "$so")"

			# 6 3-threaded
			sc="$(select_cohort "$destResc" "$sr" "$sc" "$st" "$mult"  6  2  3 < "$so")"

			# 4 4--5-threaded
			sc="$(select_cohort "$destResc" "$sr" "$sc" "$st" "$mult"  4  3  5 < "$so")"

			# 3 6--7-threaded
			sc="$(select_cohort "$destResc" "$sr" "$sc" "$st" "$mult"  3  5  7 < "$so")"

			# 2 8--15-threaded
			sc="$(select_cohort "$destResc" "$sr" "$sc" "$st" "$mult"  2  7 15 < "$so")"

			# 1 16-threaded
			sc="$(select_cohort "$destResc" "$sr" "$sc" "$st" "$mult"  1 15    < "$so")"

			: $(( cnt += sc ))
		fi

		rm --force "$so"
	done
}

resolve_opts() {
	local mapVar="$1"
	shift

	local opts
	if ! opts="$(format_opts "$@")"; then
		return 1
	fi

	eval set -- "$opts"

	local reqRescs=true

	while true; do
		case "$1" in
			-c|--collection)
				eval "$mapVar""[collection]='$2'"
				shift 2
				;;
			-d|--dbms)
				PGHOST="$2"
				shift 2
				;;
			--dbms-port)
				PGPORT="$2"
				shift 2
				;;
			-h|--help)
				eval "$mapVar"'[help]=help'
				reqRescs=false
				shift
				;;
			-m|--multiplier)
				eval "$mapVar""[multiplier]='$2'"
				shift 2
				;;
			-U|--user)
				PGUSER="$2"
				shift 2
				;;
			-v|--version)
				eval "$mapVar"'[version]=version'
				reqRescs=false
				shift
				;;
			--)
				shift
				break
				;;
			*)
				printf 'INTERNAL ERROR: failed to resolve command line options\n' >&2
				return 1
				;;
		esac
	done

	if [[ "$reqRescs" == false ]]; then
		return 0
	fi

	if (( $# < 2 )); then
		return 1
	fi

	eval "$mapVar""[src-resc]='$1'"
	eval "$mapVar""[dest-resc]='$2'"
}

finish() {
	local objList="$1"

	rm --force "$objList"
	eval "exec 1>&$Log $Log>&-"
}

count_list() {
	awk 'BEGIN {
			RS = "\0"
			tot = 0
		}

		{ tot = tot + 1 }

		END { print tot }'
}

count_unmovable() {
	local baseCond="$1"
	local srcResc="$2"
	local destResc="$3"

	psql --no-align --quiet --tuples-only ICAT  <<EOSQL
SELECT COUNT(data_id)
FROM r_data_main AS d JOIN r_coll_main AS c ON c.coll_id = d.coll_id
WHERE d.data_id = ANY(ARRAY(
		SELECT data_id FROM r_data_main WHERE ($(mk_resc_restrict_cond resc_id "$srcResc"))
		INTERSECT SELECT data_id
			FROM r_data_main
			WHERE resc_id IN (SELECT resc_id FROM r_resc_main WHERE resc_name = '$destResc')))
	AND ($baseCond);
EOSQL
}

mk_resc_restrict_cond() {
	local rescCol="$1"
	local resc="$2"

cat <<SQL
$rescCol IN (
	WITH RECURSIVE child_mapping AS (
		SELECT resc_id AS id, (resc_net != 'EMPTY_RESC_HOST') AS storage, resc_name AS root
			FROM r_resc_main
			WHERE resc_name = '$resc'
		UNION SELECT r.resc_id, r.resc_net != 'EMPTY_RESC_HOST', m.root
			FROM r_resc_main AS r
				JOIN child_mapping AS m
					ON m.id = CASE WHEN r.resc_parent::TEXT = ''
						THEN NULL
						ELSE r.resc_parent::BIGINT END )
	SELECT id FROM child_mapping WHERE storage )
SQL
}

format_opts() {
	getopt \
		--name "$ExecName" \
		--longoptions collection:,dbms:,dbms-port:,help,multiplier:,user:,version \
		--options c:d:hm:U:v \
		-- \
		"$@"
}

list_src_resc() {
	cut --zero-terminated --delimiter=' ' --fields=1 | sort --unique --zero-terminated | tr '\0' '\n'
}

partition() {
	local minSizeB="$1"

	local maxSizeB
	if (( $# >= 2 )); then
		maxSizeB="$2"
	fi

	if [[ -n "${maxSizeB-}" ]]; then
		awk --assign min="$minSizeB" --assign max="$maxSizeB" \
			'BEGIN {
				RS = "\0"
				FS = " "
				ORS = "\0"
			}

			{
				if ($1 >= min && $1 < max) { print substr($0, length($1) + 2) }
			}'
	else
		awk --assign min="$minSizeB" \
			'BEGIN {
				RS = "\0"
				FS = " "
				ORS = "\0"
			}

			{
				if ($1 >= min) { print substr($0, length($1) + 2) }
			}'
	fi
}

track_prog() {
	local cnt="$1"
	local tot="$2"
	local subTot="$3"

	local subCnt=0
	local msg=

	while read -r; do
		((++subCnt))
		((++cnt))
		printf '\r%*s\r' "${#msg}" '' >&2
		printf -v msg \
			'cohort: %0*d/%d, all: %0*d/%d' \
			"${#subTot}" "$subCnt" "$subTot" "${#tot}" "$cnt" "$tot"
		printf '%s' "$msg" >&2
	done

	printf '\r%*s\rcohort: %0*d/%d, all: %0*d/%d\n' \
			"${#msg}" '' "${#subTot}" "$subCnt" "$subTot" "${#tot}" "$cnt" "$tot" \
		>&2

	printf '%s' "$cnt"
}

select_cohort() {
	local destResc="$1"
	local srcResc="$2"
	local cnt="$3"
	local tot="$4"
	local mult="$5"
	local maxProcs="$6"
	local minThreads="$7"

	local maxThreads
	if (( $# >= 8 )); then
		maxThreads="$8"
	fi

	local minSizeMiB=$((minThreads * 32))
	local minSizeB=$(( minSizeMiB * 1024**2 ))

	local cohortList
	cohortList="$(mktemp)"

	local maxSizeMiB
	if [[ -n "${maxThreads-}" ]]; then
		maxSizeMiB=$((maxThreads * 32))
		local maxSizeB=$(( maxSizeMiB * 1024**2 ))

		partition "$minSizeB" "$maxSizeB"
	else
		partition "$minSizeB"
	fi > "$cohortList"

	local subTotal
	subTotal="$(count_list <"$cohortList")"

	if [[ -n "${maxSizeMiB-}" ]]; then
		printf 'Physically moving %s files with size in [%s, %s) MiB\n' \
				"$subTotal" "$minSizeMiB" "$maxSizeMiB" \
			>&2
	else
		printf 'Physically moving %s files with size >= %s MiB\n' "$subTotal" "$minSizeMiB" >&2
	fi

	if (( subTotal > 0 )); then
		local maxArgs=$(( 2 * maxProcs**2 ))
		maxProcs=$((maxProcs * mult))

		xargs --null --max-args "$maxArgs" --max-procs "$maxProcs" \
				iphymv -M -v -R "$destResc" -S "$srcResc" \
			< "$cohortList" \
			2>&"$Log" \
			| tee >(cat >&"$Log") \
			| track_prog "$cnt" "$tot" "$subTotal"
	else
		printf '%s\n' "$cnt"
	fi

	rm --force "$cohortList"
	return 0
}

main "$@"
