#! /bin/bash

readonly ExecName=$(basename $0)
readonly Version=2


show_help()
{
  cat <<EOF

$ExecName version $Version

Usage:
 $ExecName [options]

Generates a report on the data objects that need to be replicated. It lists the
number of unreplicated data objects and their volume broken down by the storage
resource holding the corresponding files.

Options:
 -H, --host <host>  connect to the ICAT's DBMS on the host <host> instead of
                    the PostgreSQL default
 -p, --port <port>  connect to the ICAT's DBMS listening on TCP port <port>
                    instead of the PostgreSQL default

 -h, --help     display help text and exit
 -v, --version  display version and exit
EOF
}


main()
{
  local opts=

  if ! opts=$(getopt --name "$ExecName" --longoptions help,host:,port:,version --options hH:p:v -- "$@")
  then
    show_help >&2
    return 1
  fi

  eval set -- "$opts"

  while true
  do
    case "$1" in
      -h|--help)
        show_help
        return 0
        ;;
      -H|--host)
        local hostArg="--host $2"
        shift 2
        ;;
      -p|--port)
        local portArg="--port $2"
        shift 2
        ;;
      -v|--version)
        show_version
        return 0
        ;;
      --)
        shift
        break
        ;;
      *)
        show_help >&2
        return 1
        ;;
    esac
  done

  mk_report_query $(date --date yesterday '+%s') | psql $hostArg $portArg ICAT icat_reader
}


mk_report_query()
{
  local maxTime="$1"

  cat <<EOSQL
SELECT resc_name AS resource, COUNT(*) AS count, SUM(data_size) / 1024 ^ 4 AS "volume (TiB)"
FROM r_data_main
WHERE data_id = ANY(ARRAY(SELECT data_id FROM r_data_main GROUP BY data_id HAVING COUNT(*) = 1))
  AND create_ts < '0$maxTime'
  AND resc_name NOT IN ('cyverseUKRes', 'haboobRes', 'unlRes')
GROUP BY resc_name
ORDER BY resc_name
EOSQL
}


show_version()
{
  printf '%s\n' "$Version"
}


set -e

main "$@"
