#! /bin/bash

readonly ExecName=$(basename $0)
readonly Version=1


show_help()
{
cat <<EOF

$ExecName version $Version

Usage:
 $ExecName [options]

Generates a report on the data objects that need to be replicated. It lists the
number of unreplicated data objects and their volume broken down by the storage
resource holding the corresponding files.

Options:
 -H, --host <host>  connect to the ICAT's DBMS on the host <host> instead of
                    the PostgreSQL default
 -p, --port <port>  connect to the ICAT's DBMS listening on TCP port <port>
                    instead of the PostgreSQL default

 -h, --help     display help text and exit
 -v, --version  display version and exit
EOF
}


show_version()
{
  printf '%s\n' "$Version"
}


set -e

readonly Opts=$(getopt --name "$ExecName" \
                       --options hH:p:v \
                       --longoptions help,host:,port:,version \
                       -- \
                       "$@")

if [ "$?" -ne 0 ]
then
  show_help >&2
  exit 1
fi

eval set -- "$Opts"

while true
do
  case "$1" in
    -h|--help)
      show_help
      exit 0
      ;;
    -H|--host)
      readonly HostArg="--host $2"
      shift 2
      ;;
    -p|--port)
      readonly PortArg="--port $2"
      shift 2
      ;;
    -v|--version)
      show_version
      exit 0
      ;;
    --)
      shift
      break
      ;;
    *)
      show_help >&2
      exit 1
      ;;
  esac
done

psql $HostArg $PortArg ICAT icat_reader <<EOSQL
SELECT resc_name AS resource, COUNT(*) AS count, SUM(data_size) / 1024 ^ 4 AS "volume (TiB)"
  FROM r_data_main
  WHERE data_id = ANY(ARRAY(SELECT data_id FROM r_data_main GROUP BY data_id HAVING COUNT(*) = 1))
    AND NOT (data_repl_num = 0 AND resc_name = 'cshlWildcatRes')
    AND coll_id IN (
        SELECT coll_id FROM r_coll_main WHERE coll_name NOT LIKE '/iplant/home/shared/aegis%')
  GROUP BY resc_name
  ORDER BY resc_name
EOSQL
