#! /bin/bash

readonly ExecName=$(basename "$0")
readonly Version=2


show_help()
{
  cat <<EOF

$ExecName version $Version

Usage:
 $ExecName [options]

replicates data objects to taccCorralRes

Options:
 -c, --collection <collection>  only replicate the data objects in this
                                collection
 -m, --multiplier <multiplier>  a multiplier on the number of processes to run
                                at once, default: 1
 -r, --resource <resource>      only replicate the data objects with a file on
                                this resource
 -u, --until <stop_time>        the time to stop replication in a format
                                understandable by `date`

 -h, --help     show help and exit
 -v, --verison  show version and exit

Summary:
This script replicates data objects to the taccCorralRes resource. It only
replicates objects that only have one replica that is not in the
/iplant/home/shared/aegis collection nor on the cshlWildcatRes resource. It
writes progress to standard error and all messages, error or otherwise, to
standard out.

Prerequisites:
 1) The user must be initialized with iRODS as an admin user.
 2) The user must be able to connect to the ICAT DB as the icat_reader user
    without providing a password.
EOF
}


show_version()
{
  printf '%s\n' "$Version"
}


exit_with_help()
{
  show_help >&2
  exit 1
}


set -e

readonly Opts=$(getopt --name "$ExecName" \
                       --options c:hm:r:u:v \
                       --longoptions collection:,help,multiplier:,resource:,until:,version \
                       -- \
                       "$@")

if [ "$?" -ne 0 ]
then
  exit_with_help
fi

eval set -- "$Opts"

while true
do
  case "$1" in
    -c|--collection)
      readonly BaseColl="$2"
      shift 2
      ;;
    -h|--help)
      show_help
      exit 0
      ;;
    -m|--multiplier)
      readonly ProcMult="$2"
      shift 2
      ;;
    -r|--resource)
      readonly SrcRes="$2"
      shift 2
      ;;
    -u|--until)
      readonly Until="$2"
      shift 2
      ;;
    -v|--version)
      show_version
      exit 0
      ;;
    --)
      shift
      break
      ;;
    *)
      exit_with_help
      ;;
  esac
done

if [ -z "$ProcMult" ]
then
  readonly ProcMult=1
fi

if [ -n "$Until" ]
then
  if ! export UNTIL_TS=$(date --date="$Until" '+%s')
  then
    printf '%s is not a valid date format\n' "$Until"
    exit 1
  fi
fi

# Redirect stdout to FD 3 to use as a logging channel
readonly Log=3
eval "exec $Log>&1"


CHECK_TIME()
{
  if [ -n "$UNTIL_TS" ] && [ $(date '+%s') -ge "$UNTIL_TS" ]
  then
    return 1
  fi
}
export -f CHECK_TIME


REPL_BATCH()
{
  if ! CHECK_TIME
  then
    exit 1
  fi

  irepl -B -M -T -v -R taccCorralRes "$@"

# XXX: Trying to figure out the irepl error code for when irepl logs a
# '_rcConnect: connectToRhost error, server on data.cyverse.org:1247 is probably
# down status = -305113 USER_SOCK_CONNECT_ERR, No route to host' error message.
# It is probably at 113, but we should confirm.
# TODO: Once this is confirmed, if this status is returned, this function should
# wait for a bit and try again.
  local replStatus="$?"
  if [ "$replStatus" -ne 0 ]
  then
    printf 'repl: irepl exited with status %d\n' "$replStatus" >&2
  fi

  exit 0
}
export -f REPL_BATCH


update_progress()
{
  printf "$@" >&2
}


finish()
{
  local objList="$1"

  if ! CHECK_TIME
  then
    update_progress 'out of time\n'
  fi

  rm --force "$objList"
  eval "exec 1>&$Log $Log>&-"
}


count()
{
  awk 'BEGIN {
         RS = "\0"
         tot = 0
       }

       { tot = tot + 1 }

       END { print tot }'
}


partition()
{
  local minSizeB="$1"

  if [ "$#" -ge 2 ]
  then
    local maxSizeB="$2"
  fi

  if [ -n "$maxSizeB" ]
  then
    awk --assign min="$minSizeB" --assign max="$maxSizeB" \
        'BEGIN {
           RS = "\0"
           FS = " "
           ORS = "\0"
         }

         {
           if ($1 >= min && $1 < max) { print substr($0, length($1) + 2) }
         }'
  else
    awk --assign min="$minSizeB" \
        'BEGIN {
           RS = "\0"
           FS = " "
           ORS = "\0"
         }

         {
           if ($1 >= min) { print substr($0, length($1) + 2) }
         }'
  fi
}


track_prog()
{
  local cnt="$1"
  local tot="$2"
  local subTot="$3"

  local subCnt=0
  local msg=

  while read -r
  do
    ((++subCnt))
    ((++cnt))
    printf '\r%*s\r' "${#msg}" '' >&2
    printf -v msg \
           'cohort: %0*d/%d, all: %0*d/%d' \
           "${#subTot}" "$subCnt" "$subTot" "${#tot}" "$cnt" "$tot"
    update_progress "$msg"
  done

  update_progress '\r%*s\rcohort: %0*d/%d, all: %0*d/%d\n' \
                  "${#msg}" '' "${#subTot}" "$subCnt" "$subTot" "${#tot}" "$cnt" "$tot"

  printf '%s' "$cnt"
}


select_cohort()
{
  local cnt="$1"
  local tot="$2"
  local maxProcs="$3"
  local minThreads="$4"

  if [ "$#" -ge 5 ]
  then
    local maxThreads="$5"
  fi

  if ! CHECK_TIME
  then
    exit 0
  fi

  local minSizeMiB=$((minThreads * 32))
  local minSizeB=$((minSizeMiB * ((1024 ** 2))))
  local cohortList=$(tempfile)

  if [ -n "$maxThreads" ]
  then
    local maxSizeMiB=$((maxThreads * 32))
    local maxSizeB=$((maxSizeMiB * ((1024 ** 2))))

    partition "$minSizeB" "$maxSizeB"
  else
    partition "$minSizeB"
  fi > "$cohortList"

  local subTotal=$(count <"$cohortList")

  if [ -n "$maxSizeMiB" ]
  then
    update_progress 'Replicating %s files with size in [%s, %s) MiB\n' \
                    "$subTotal" "$minSizeMiB" "$maxSizeMiB"
  else
    update_progress 'Replicating %s files with size >= %s MiB\n' "$subTotal" "$minSizeMiB"
  fi

  if [ "$subTotal" -gt 0 ]
  then
    local maxArgs=$((2 * ((maxProcs ** 2))))
    maxProcs=$((maxProcs * ProcMult))

    parallel --no-notice --null --halt 2 --max-args "$maxArgs" --max-procs "$maxProcs" REPL_BATCH \
        < "$cohortList" \
        2>&"$Log" \
        | tee >(cat >&"$Log") \
        | track_prog "$cnt" "$tot" "$subTotal"
  else
    printf '%s\n' "$cnt"
  fi

  rm --force "$cohortList"
}


readonly ObjectList=$(tempfile)

trap "finish $ObjectList" EXIT

if ! iadmin lz &> /dev/null
then
  printf "aren't authenticated as a rodsadmin user\n" >&2
  exit 1
fi

if ! psql --host irods-db3 ICAT icat_reader <<< '' &> /dev/null
then
  printf "aren't able to connect to the ICAT DB as the icat_reader without a password\n" >&2
  exit 1
fi

if ! CHECK_TIME
then
 printf 'Stop time is in the past\n' >&2
 exit 1
fi

update_progress 'Retrieving data objects to replicate...\n'

if [ -n "$SrcRes" ]
then
  readonly SrcCond="d.resc_name = '$SrcRes'"
else
  readonly SrcCond=TRUE
fi

if [ -n "$BaseColl" ]
then
  readonly BaseCond="c.coll_name = '$BaseColl' OR c.coll_name LIKE '$BaseColl/%'"
else
  readonly BaseCond=TRUE
fi

psql --no-align --tuples-only --record-separator-zero --field-separator ' ' --host irods-db3 \
     ICAT icat_reader \
<<EOSQL > "$ObjectList"
SELECT d.data_size, c.coll_name || '/' || d.data_name
  FROM r_data_main AS d JOIN r_coll_main AS c ON c.coll_id = d.coll_id
  WHERE d.data_id = ANY(ARRAY(SELECT data_id FROM r_data_main GROUP BY data_id HAVING COUNT(*) = 1))
    AND NOT (d.data_repl_num = 0 AND d.resc_name = 'cshlWildcatRes')
    AND c.coll_name != '/iplant/home/shared/aegis'
    AND c.coll_name NOT LIKE '/iplant/home/shared/aegis/%'
    AND ($BaseCond)
    AND ($SrcCond)
EOSQL

readonly Tot=$(count < "$ObjectList")
update_progress '%d data objects to replicate\n' "$Tot"

if [ "$Tot" -gt 0 ]
then
  cnt=0
  cnt=$(select_cohort "$cnt" "$Tot"  16   0  1 < "$ObjectList")  # 16 1-threaded transfers
  cnt=$(select_cohort "$cnt" "$Tot"   8   1  2 < "$ObjectList")  # 8 2-threaded
  cnt=$(select_cohort "$cnt" "$Tot"   6   2  3 < "$ObjectList")  # 6 3-threaded
  cnt=$(select_cohort "$cnt" "$Tot"   4   3  5 < "$ObjectList")  # 4 4--5-threaded
  cnt=$(select_cohort "$cnt" "$Tot"   3   5  7 < "$ObjectList")  # 3 6--7-threaded
  cnt=$(select_cohort "$cnt" "$Tot"   2   7 15 < "$ObjectList")  # 2 8--15-threaded
  cnt=$(select_cohort "$cnt" "$Tot"   1  15    < "$ObjectList")  # 1 16-threaded
fi
