#! /bin/bash

set -e

readonly EXEC_NAME=$(basename $0)
readonly VERSION=1


show_help()
{
cat << EOF

$EXEC_NAME version $VERSION

Usage:
  $EXEC_NAME

This script generates a list of root resources sorted by their creation times. It requires the
iCommands to be installed and a session to have been already initiated.

Options:
 -h, --help     display help text and exit
 -v, --version  display version and exit
EOF
}


show_version()
{
  printf '%s\n' "$VERSION"
}


if ! readonly Opts=$(getopt --name "$EXEC_NAME" --options hv --longoptions help,version -- "$@")
then
  show_help >&2
  exit 1
fi

eval set -- "$Opts"

while true
do
  case "$1" in
    -h|--help)
      show_help
      exit 0
      ;;
    -v|--version)
      show_version
      exit 0
      ;;
    --)
      shift
      break
      ;;
    *)
      show_help >&2
      exit 1
      ;;
  esac
done

iquest \
    '%s %s' \
    "SELECT ORDER(RESC_CREATE_TIME), RESC_NAME \
     WHERE RESC_PARENT = '' AND RESC_CLASS_NAME != 'bundle'"
