#!/usr/bin/env bash

ExecName=$(basename "$0")
readonly ExecName

readonly Version=1


show_help()
{
cat <<EOF

$ExecName version $Version

Usage:
  $ExecName

This script generates a list of root resources sorted by their creation times. It requires the
iCommands to be installed and a session to have been already initiated.

Options:
 -h, --help     display help text and exit
 -v, --version  display version and exit
EOF
}


show_version()
{
  printf '%s\n' "$Version"
}


set -e

main()
{
  if ! opts=$(getopt --name "$ExecName" --options hv --longoptions help,version -- "$@")
  then
    show_help >&2
    exit 1
  fi

  eval set -- "$opts"

  while true
  do
    case "$1" in
      -h|--help)
        show_help
        exit 0
        ;;
      -v|--version)
        show_version
        exit 0
        ;;
      --)
        shift
        break
        ;;
      *)
        show_help >&2
        exit 1
        ;;
    esac
  done

  iquest \
      '%s %s' \
      "SELECT RESC_LOC, ORDER(RESC_CREATE_TIME) \
       WHERE RESC_TYPE_NAME = 'unixfilesystem' AND RESC_CLASS_NAME != 'bundle'" \
    | convert_create_times
}


convert_create_times()
{
  local createTS host
  while read -r host createTS; do
    local createTime
    createTime="$(date --iso-8601 --date=@"$createTS")"
    printf '%s\t%s\n' "$createTime" "$host"
  done
}


main "$@"