#! /bin/bash

set -e

readonly EXEC_NAME=$(basename $0)
readonly VERSION=1


print_help()
{
cat << EOF
$EXEC_NAME version $VERSION

Usage:
  $EXEC_NAME

This script generates a list of root resources sorted by their creation times. It requires the
iCommands to be installed and a session to have been already initiated.

Options:
 -h, --help     display help text and exit
 -v, --version  display version and exit
EOF
}


print_version()
{
  printf '%s\n' "$VERSION"
}


if ! opts=$(getopt --name "$EXEC_NAME" --options hv --longoptions help,version -- "$@")
then
  printf '\n' >&2
  print_help >&2
  exit 1
fi

eval set -- "$opts"

while true
do
  case "$1" in
    -h|--help)
      print_help
      exit 0
      ;;
    -v|--version)
      print_version
      exit 0
      ;;
    --)
      shift
      break
      ;;
    *)
      printf '\n' >&2
      print_help >&2
      exit 1
      ;;
  esac
done

iquest \
    '%s %s' \
    "SELECT ORDER(RESC_CREATE_TIME), RESC_NAME \
     WHERE RESC_PARENT = '' AND RESC_CLASS_NAME != 'bundle'"
