#! /bin/bash
#
# This script deletes the trash older than one month for every user.
#

readonly AMonth=$((31 * 24 * 60))

if ! iadmin lz &> /dev/null
then
  printf "aren't authenticated as a rodsadmin user\n"
  exit 1
fi

while IFS=\# read -r user zone
do
  if [ "$zone" != iplant ]
  then
    user="$user"\#"$zone"
  fi

  if [ "$user" == anonymous -o "$user" == rodsBoot ]
  then
    continue
  fi

  printf 'removing trash for %s\n' "$user"
  irmtrash -M -u "$user" --age "$AMonth"
done < <(iadmin lu | sort)
