#!/usr/bin/awk -f
#
# This script extracts the begin and end times for each session from a stream of
# iRODS sessions. It writes one interval per line with the following format.
#
# <start time> <end time> <client user>
#
# The times are in seconds since the POSIX epoch.


function read_time(entry) {
  split(entry, parts, " ");
  date = gensub(/-/, " ", "g", parts[1]);
  time = gensub(/:/, " ", "g", parts[2]);
  return mktime(date " " time " MST");
}


function read_user(entry) {
  return gensub(/.*cuser=([^ ]*) .*/, "\\1", 1, entry);
}


function print_interval(startTime, endTime, user) {
  print startTime " " endTime " " user
}


BEGIN {
  RS = "§";
  FS = "•";
}


$2 ~ /cuser=/ {
  print_interval(read_time($2), read_time($NF), read_user($2));
}
