#!/usr/bin/env bash
#
# This script bundles an iRODS collection into chunks for efficient transfer.
#
# Usage: chunk COLL-PATH
#
# Parameters:
#    COLL-PATH  The absolute path to the iRODS collection to chunk
#
# This script breaks bundles all of the data objects in COLL-PATH that have on
# the default resource for the first catalog service provider. For each storage
# resource under the default resource, it archives all of the replicas on this
# storage resource that belong to a data object in COLL-PATH, splitting the
# archive into data objects no larger that 100 GiB in size. Let COLL-NAME be
# the base name of the collection being chunked. For a store resource named
# RESC, its archive chunks will be named "COLL-NAME.RESC-??" where ? is
# lowercase letter between "a" and "z", inclusive. The chunks are generated in
# lexicographic order so that if the are concatenated using
# `cat COLL-NAME.RESC-*`, the full archive will be rebuilt correctly. All chunks
# for all storage resources are stored in the collection "COLL-PATH.chunked".
#
# © 2026, The Arizona Board of Regents on behalf of The University of Arizona.
# For license information, see https://cyverse.org/license.

set -o errexit -o nounset -o pipefail

EXEC_DIR="$(dirname "$(realpath --canonicalize-missing "$0")")"
readonly EXEC_DIR

readonly CHUNKED_EXT=chunked
readonly CHUNKING_LOG_SUFFIX=-chunk.log
readonly IRODS_SVC_ACNT=irods
readonly TMP_DIR=/tmp

main() {
	if (( $# < 1 )); then
		printf 'The absolute path to the collection to chunk is required\n' >&2
		return 1
	fi

	local srcColl="$1"

	local destColl="$srcColl"."$CHUNKED_EXT"
	imkdir -p "$destColl"

	local acls
	readarray -t acls <<< "$(get_acl "$srcColl")"

	local acl
	for acl in "${acls[@]}"; do
		local user perm
		read -r user perm <<< "$acl"
		ichmod -M "$perm" "$user" "$destColl"
	done

	ichmod inherit "$destColl"

	local rescs
	readarray -t rescs <<< "$(get_storage_rescs "$(determine_default_resc)" "$srcColl")"

	local resc
	for resc in "${rescs[@]}"; do
		local svr
		svr="$(quest %s <<<"select RESC_LOC where RESC_NAME = '$resc'")"

		scp -q "$EXEC_DIR"/chunk-resc "$svr":chunk-resc
		ssh -n -q "$svr" sudo mv --force chunk-resc "'$TMP_DIR'"/chunk-resc
		ssh -n -q "$svr" sudo chmod +x "'$TMP_DIR'"/chunk-resc
		ssh -n -q "$svr" sudo chown "'$IRODS_SVC_ACNT'" "'$TMP_DIR'"/chunk-resc

		ssh -n -q "$svr" \
			sudo --background --login --non-interactive --user="'$IRODS_SVC_ACNT'" \
					"'$TMP_DIR'"/chunk-resc \
						"'$resc'" "'$srcColl'" "'$destColl'" "'$TMP_DIR/$resc$CHUNKING_LOG_SUFFIX'" \
				'&>' /dev/null

		printf 'Launched on %s\n' "$svr"
	done
}

determine_default_resc() {
	local zone
	zone="$(quest %s <<<"select ZONE_NAME where ZONE_TYPE = 'local'")"

	izonereport | default_resc_from_zonereport "$zone"
}

default_resc_from_zonereport() {
	local zone="$1"

	jq --raw-output --from-file /dev/stdin <(cat) <<JQ
.zones
	| map(select(.servers[0].server_config.zone_name = "$zone"))
	| .[0].servers[0].service_account_environment.irods_default_resource
JQ
}

get_storage_rescs() {
	local rootResc="$1"
	local coll="$2"

	quest %s <<EOQ
select RESC_NAME
where DATA_RESC_HIER = '$rootResc' || like '$rootResc;%' and COLL_NAME = '$coll' || like '$coll/%'
EOQ
}

get_acl() {
	local coll="$1"

	quest '%s#%s %s' <<EOF
select COLL_USER_NAME, COLL_ZONE_NAME, COLL_ACCESS_NAME where COLL_NAME = '$coll'
EOF
}

quest() {
	local fmt="$1"

	local query=''

	local line
	while read -r line; do
		query+=" $line"
	done

	iquest --no-page "$fmt" "${query//$'\t'/ }" | sed '/^CAT_NO_ROWS_FOUND: /d' || true
}

main "$@"
